- name: Configure IIS and deploy LogViewer
  hosts: logviewer
  gather_facts: no

  vars_files:
    - ../group_vars/logviewer.vault.yml
  roles:
    - iis_base
    - db_migrations
    - logviewer_app
    - blue_green_switch
    - monitoring_validation
