ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
ansible_winrm_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"

aws_region: us-east-2
rds_secret_arn: "{{ lookup('env', 'RDS_SECRET_ARN') }}"
alb_listener_arn: "{{ lookup('env', 'ALB_LISTENER_ARN') }}"
tg_green_arn: "{{ lookup('env', 'TG_GREEN_ARN') }}"
alb_dns_name: "{{ lookup('env', 'ALB_DNS_NAME') }}"

# Optional SNS topic for alerts (only used if defined and non-empty)
sns_topic_arn: "{{ lookup('env', 'SNS_TOPIC_ARN') | default('', true) }}"