
dotnet_hosting_bundle_url: "{{ lookup('env', 'DOTNET_HOSTING_URL') | default('https://example.com/dotnet-hosting-8.0.16-win.exe', true) }}"

logviewer_app_version: "1.0.0.1"

ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
ansible_winrm_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
aws_region: us-east-2           # matches your Terraform region
rds_secret_arn: "{{ lookup('env', 'RDS_SECRET_ARN') }}"
alb_dns_name: "{{ lookup('env', 'ALB_DNS_NAME') }}"

# Optional SNS
sns_topic_arn: "{{ lookup('env', 'SNS_TOPIC_ARN') | default('', true) }}"

tg_green_arn: "{{ lookup('env', 'TG_GREEN_ARN') }}"
tg_blue_arn: "{{ lookup('env', 'TG_BLUE_ARN') | default('', true) }}"